### PR TITLE
sort pages and images into folders

### PR DESCRIPTION
**Pull request by ihaveamac**
turns out you can use folders. so I moved them. and edited the pages so they worked with them.

you can see the results at https://github.com/ihaveamac/3DS-Homebrew-Menu-Wiki/wiki which has the same contents as https://github.com/ihaveamac/3DS-Homebrew-Menu-Wiki!

if this doesn't work, then I can look into it, and reverse it if it can't be fixed with folders.

### CODE REVIEW

**Comment by RedTopper** [comment]
Holy cow! Thanks, I'll see if this works, but it looks like it does.

Gosh darn GitHub always bamboozling me.

**Comment by ihaveamac** [comment]
I forgot some things. sigh.

**Comment by RedTopper** [comment]
Alright, are you going to open another pull request? Or do you need me to do something?
Thanks, btw!

**Comment by ihaveamac** [comment]
I'll just make yet another pull req.

**Comment by RedTopper** [comment]
Haha, thanks!

**Comment by mashers** [comment]
That's much better! Thanks buddy! :)

**Pull request merged**
